FORMAT: 1A
HOST: https://api.alooga.com.br/

# Alooga

Seja bem-vindo(a) a documentação da API do Alooga.

# Apresentação

Nós criamos nossa API seguindo a técnica REST. Dessa forma, nossas URLs são amigáveis e previsíveis. Todas nossas APIs respondem em JSON.

Todas nossas chamadas são feitas (na versão mais atual da API) na URL https://api.alooga.com.br


# Autenticação

A autenticação na API é feita através da utilização de um API Token. Cada usuário tem um Token que é enviado quando se cadastra ou loga.

Para autenticar você deve passar o e-mail e o token do usuário no header de cada chamada.

Todas as chamadas devem ser feitas via HTTPS e devem conter a autenticação.

### Exemplo de header
```
    
    Authorization: Token token="V7u63mYTeidFncA", email="email@domain.com"

```

# Erros

A API utiliza os próprios Códigos de Status HTTP para indicar sucesso ou falha da chamada. Em geral os códigos iniciados com 2 indicam sucesso, os iniciados com 4 indicam erro (Ex: Falta de parâmetro obrigatório) e iniciados com 5 indicam erro interno nos servidores do Alooga.

**Resposta de Erro**

```apib
    errors  ==> Pode conter tanto uma string de erro como um hash contendo o atributo e seus erros.
```

**Ex de Erro de Autenticação (Status 401)**

```
    {
        "errors": "Unauthorized"
    }
```

**Ex de Erro de Parâmetro (Status 422)**

```
    {
        "errors": {
            "due_date": [
                "should not be in the past"
            ]
        }
    }
```

## Products [/products{?category,checkin,checkout,latitude,longitude,page,per_page,priceFrom,priceTo,search,status}]


### List/Search all products [GET]
Você pode listar os produtos ou fazer busca.

+ Parameters

    + category (number, optional) - Id de uma sub-categoria
    + checkin (string, optional) - Data inicial, ex: 19/01/2016
    + checkout (string, optional) - Data inicial, ex: 19/01/2016
    + latitude (float, optional) - Latitude da região a ser buscada
    + longitude (float, optional) - Longitude da região a ser buscada
    + page (number, optional) - Número da página para filtro
        + Default: `1`
    + per_page (number, optional) - Quantidade de registros por página
        + Default: `12`
    + priceFrom (number, optional) - Preço do produto a partir desse valor
        + Default: `5`
    + priceTo (number, optional) - Preço do produto até esse valor
        + Default: `1000`
    + search (string, optional) - Texto da busca
    + status (boolean, optional) - Mostra produtos inativos (apenas para usuários autenticados)
        + Default: `true`

+ Response 200 (application/json)

        [
            {
              "products": [
                {
                  "category_id": 14,
                  "user_id": 5,
                  "id": 81,
                  "price_centavos": 27000,
                  "price_currency": "BRL",
                  "status": true,
                  "street": "RUA VERBO DIVINO",
                  "apt": "61A T2",
                  "city": "SAO PAULO",
                  "state": "SP",
                  "country": "Brazil",
                  "zip": "04719-002",
                  "longitude": -46.7049968,
                  "latitude": -23.6336355,
                  "directions": null,
                  "name": "Relógio Bvlgari Original - Aço/Borracha/Fibra de Carbono",
                  "description": "Relógio Bvlgari com design esportivo e arrojado.",
                  "details": "- Pulseira de borracha ajustável;\n- Caixa em aço e fundo em fibra de carbono;\n- Automático.",
                  "intro": null,
                  "calendar": 2,
                  "minimum": null,
                  "maximum": null,
                  "created_at": "2015-06-30T23:32:17.269-03:00",
                  "updated_at": "2015-06-30T23:33:57.136-03:00",
                  "views": null,
                  "dates": null,
                  "rental_dates": [
                    
                  ],
                  "photos": [
                    {
                      "id": 167,
                      "product_id": 81,
                      "thumbnail": "https://alooga-photos.s3.amazonaws.com/uploads/products/81/thumb_3ded8676-1b16-4bba-b9da-2d8a753abb30.JPG",
                      "image": "https://alooga-photos.s3.amazonaws.com/uploads/products/81/3ded8676-1b16-4bba-b9da-2d8a753abb30.JPG"
                    }
                  ],
                  "rental_ids": [
                    44
                  ]
                }
        ]


### Create a New Product [POST]

Envia um hash com os parametros do produto

+ Request (application/json)

        {
            "product": {
                "name" : "produto 1",
                "price" : "100,00"
            }
        }

+ Response 201 (application/json)

    + Headers

            Location: /products/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }


## Users [/users]


### Recuperar senha [/users/recoverypass] [POST]
### Atualizar senha [/users/updatepassword][POST]
### Link de confirmação da conta para quem recebeu email [/users/confirmation][POST]
### Start do login via facebook [/auth/authorized][POST]
### Validação de login via facebook [/users/minha-conta/confirmar/{confirmation_token}] [GET]
### Cadastro de usuário [/users/signup] [POST]

### Atualiza a foto [/users/{id}/photo']  [POST]
### Envia arquivo/foto de identidade [/user/check/id']  [POST]
### Envia arquivo/foto de cpf [/user/check/cpf']  [POST]
### Adiciona dados bancários [/users/addBank']  [POST]
### Adiciona cartão de crédito [/users/addCard']  [POST]
### Atualiza apenas a senha [/users/newpassword']  [POST]

## Categories [/categories]
## Messages [/messages]
## Reviews [/reviews]
    only: [:index, :show, :create]
## Favorites [/favorites]
    only: [:index, :create, :destroy]
## Payments Methods [/payment_methods]
    Para salvar os cartões de créditos
    only: [:index, :show, :create, :update, :destroy]
## Payments [/payments]
    only: [:index, :show, :create, :update, :destroy]

## Notifications [/notifications]
    only: [:index, :update]
### Clear all [POST]
    Apaga todas as notificações do usuário

## Search [/search] [GET]

## Rentals [/rentals]
### Aprova o aluguel [/rentals/{id}/approve] [GET]
### Recusa o aluguel [/rentals/{id}/recuse]  [GET]
### Cancela o aluguel [/rentals/{id}/cancel]  [GET]

## Photos [/photos]
    only: [:index, :create, :show, :destroy]
### Adiciona foto ao produto [/photos/{product}] [POST]
### Lista fotos do produto [/photos/{product}] [GET]
### Deleta uma foto [/photos/{id}] [DELETE]

